apiVersion: v2
name: ska-tmc-testing-low
description: An umbrella Helm chart for SKA-TMC-Low deployment.
type: application
version: 0.1.0
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Kalyani Thigale
    email: kalyanit.ska@gmail.com
  - name: Shraddha Bajare
    email: shraddhab.ska@gmail.com
dependencies:
  - name: ska-tango-util
    version: 0.3.9
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 0.3.10
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tmc-low
    version: 0.1.0
    repository: file://../ska-tmc-low
    alias: tmc-low
    condition: tmc-low.enabled
  - name: ska-ser-skuid
    version: 0.3.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-skuid.enabled
