[tool.poetry]
name = "ska-tmc-integration"
version = "0.6.10"
description = "Repository for integration of TMC components"
authors = ["Team Himalaya", "Team Sahyadri"]
license = "BSD-3-Clause"

include = [
    { path = 'tests'}
]

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = "3.10.6"
ska-control-model="0.3.1"
ska-tango-base="0.17.0"
numpy = "1.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
