apiVersion: v2
name: ska-tmc-testing
description: An umbrella Helm chart for SKA-TMC-Mid deployment.
type: application
version: 0.0.2
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Kalyani Thigale
    email: kalyanit.ska@gmail.com
  - name: Shraddha Bajare
    email: shraddhab.ska@gmail.com
dependencies:
- name: ska-tango-util
  version: 0.3.9
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tmc-mid
  version: 0.1.0
  repository: file://../ska-tmc-mid
  alias: tmc-mid
- name: ska-ser-skuid
  version: 0.3.0
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-ser-skuid.enabled
- name: ska-tango-taranta-dashboard
  version: 1.3.0
  repository: https://artefact.skao.int/repository/helm-internal
  condition: taranta-dashboard.ingress.enabled
- name: ska-tango-taranta-dashboard-pvc
  version: 1.3.0
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-taranta
  version: 1.3.1
  repository: https://artefact.skao.int/repository/helm-internal
  condition: taranta.ingress.enabled
- name: ska-tango-tangogql
  version: 1.3.1
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-taranta-auth
  version: 0.1.5
  repository: https://artefact.skao.int/repository/helm-internal
  condition: taranta-auth.ingress.enabled