display: ":0"
xauthority: "~/.Xauthority"

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.5
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.9
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

taranta:
  ingress:
    enabled: false
    nginx: true
    hostname: test-taranta.k8s.stfc.skao.int

taranta-dashboard:
  ingress:
    enabled: false
    nginx: true
    hostname: test-taranta.k8s.stfc.skao.int

taranta-auth:
  ingress:
    enabled: false
    nginx: true
    hostname: test-taranta.k8s.stfc.skao.int


## tmc
tmc-mid:
  deviceServers:
    centralnode:
      enabled: true
    
    subarraynode:
      enabled: true

    sdpsubarrayleafnode:
      enabled: true

    sdpmasterleafnode:
      enabled: true
   
    mocks:
      enabled: true
 
## SKUID
ska-ser-skuid:
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01