---
enabled: true

system: OSO
subsystem: ska-oso-tmcsim

global:
  minikube: false
  tango_host: tango-databaseds:10000
  exposeAllDS: false
  operator: true

dsconfig:
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.8.1
    pullPolicy: IfNotPresent


labels:
  app: ska-oso-tmcsim
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

deviceServers:
  tmcsimskamid:
    enabled: true
    instances: ["01"]
    file: "data/tmcsim_ska_mid.yaml"
    baseUri: "ska_mid"
  tmcsimskalow:
    enabled: true
    instances: ["01"]
    file: "data/tmcsim_ska_low.yaml"
    baseUri: "ska_low"

# Do not deploy the tango test device by default
# Comment out these lines if test device is required
ska-tango-base:
  deviceServers:
    tangotest:
      instances: []


image:
  registry: artefact.skao.int
  image: ska-oso-tmcsim
  tag: ~  # Defaults to the chart appVersion if not set
  pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
