---
enabled: true

system: OSO
subsystem: ska-oso-tmcsim

global:
  minikube: true
  tango_host: tango-databaseds:10000

labels:
  app: ska-oso-tmc-integration-tests
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG
dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

deviceServers:
  tmcsimskamid:
    enabled: true
    instances: ["01"]
    file: "data/tmcsim_ska_mid.yaml"
    baseUri: "ska_mid"
  tmcsimskalow:
    enabled: true
    instances: ["01"]
    file: "data/tmcsim_ska_low.yaml"
    baseUri: "ska_low"

image:
  registry: artefact.skao.int
  image: ska-oso-tmc-integration-tests
  tag: ~  # Defaults to the chart appVersion if not set
  pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
