---
enabled: true

system: OSO
telescope: SKA-mid
subsystem: ska-oso-tmcsim

global:
  minikube: true
  tango_host: tango-databaseds:10000

labels:
  app: ska-oso-tmcsim
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG
dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

deviceServers:
  tmcsim:
    enabled: true
    instances: ["01"]
    file: "data/tmcsim.yaml"

image:
  registry: artefact.skao.int
  image: ska-oso-tmc-integration-tests
  tag: ~  # Defaults to the chart appVersion if not set
  pullPolicy: IfNotPresent

devpod:
  enabled: false
  # set this to a directory mountable via NFS from the pod
  hostPath: /path/to/your/src/directory
  env:
    oda_url: ~  # set dynamically in makefile

nodeSelector: {}

affinity: {}

tolerations: []
