
centralnode = "ska_low/tm_central/central_node"
tmc_subarraynode1 = "ska_low/tm_subarray_node/1"
tmc_subarraynode2 = "ska_low/tm_subarray_node/2"
tmc_subarraynode3 = "ska_low/tm_subarray_node/3"
tmc_csp_master_leaf_node = "ska_low/tm_leaf_node/csp_master"
tmc_sdp_master_leaf_node = "ska_low/tm_leaf_node/sdp_master"
sdp_subarray1 = "low-sdp/subarray/01"
sdp_subarray2 = "low-sdp/subarray/02"
sdp_subarray3 = "low-sdp/subarray/03"
csp_subarray1 = "low-csp/subarray/01"
csp_subarray2 = "low-csp/subarray/02"
csp_subarray3 = "low-csp/subarray/03"
sdp_master = "low-sdp/control/0"
csp_master = "low-csp/control/0"