global:
  minikube: false
  operator: true
  exposeALLDS: false

labels: 
  app: ska-tmc-integration

# DISH LMC
ska-mid-dish-manager:
  labels:
    app: ska-tmc-integration
  enabled: true


ska-mid-dish-simulators:
  labels:
    app: ska-tmc-integration
  enabled: true
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

ska-mid-dish-ds-manager:
  labels:
    app: ska-tmc-integration
  enabled: true
