global:
  minikube: false

# DISH LMC
ska-mid-dish-manager:
  enabled: true

ska-mid-dish-simulators:
  enabled: true
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

ska-mid-dish-ds-manager:
  enabled: true
