display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-tmc-mid

labels:
  app: ska-tmc-mid
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000

  ##  Order of instances resolution ##
  # .Values.global.dishes & .Values.global.subarray_count
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster, deviceServers.dishleafnode
  dish_devices: ["dishmaster", "dishleafnode"]
  dishes: ["01", "02", "03", "04"]

  # subarray_count, this will be expanded (1 to N inclusive) and applied to instances of:
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"
  subarray_count: 3

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.5
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-centralnode
    tag: 0.3.21
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-subarraynode
    tag: 0.3.33
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.8.23
    pullPolicy: IfNotPresent

cspmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.1.11
    pullPolicy: IfNotPresent

cspsubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.1.14
    pullPolicy: IfNotPresent

dishleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-dishleafnode
    tag: 0.1.11
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  centralnode:
    enabled: true
    instances: ["01"]
    subarray_count: 3
    file: "data/centralnode_mid.yaml"
    CspMasterLeafNodeFQDN: "ska_mid/tm_leaf_node/csp_master"
    CspMasterFQDN: "mid-csp/control/0"
    SdpMasterLeafNodeFQDN: "ska_mid/tm_leaf_node/sdp_master"
    SdpMasterFQDN: "mid_sdp/elt/master"
    DishLeafNodePrefix: "ska_mid/tm_leaf_node/d"
    NumDishes: 4

  subarraynode:
    enabled: true
    instances: ["01", "02", "03"]
    file: "data/subarraynode_mid.yaml"

  sdpsubarrayleafnode:
    enabled: true
    instances: ["01", "02", "03"]
    file: "data/sdpsubarrayleafnode.yaml"

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    SdpMasterFQDN: "mid_sdp/elt/master"

  cspmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"
    CspMasterFQDN: "mid-csp/control/0"

  cspsubarrayleafnode:
    enabled: true
    instances: ["01", "02", "03"]
    file: "data/cspsubarrayleafnode.yaml"

  dishleafnode:
    enabled: true
    instances: ["01", "02", "03", "04"]
    file: "data/dishleafnode.yaml"

  mocks:
    enabled: false
    file: "data/mocks.yaml"


nodeSelector: {}

affinity: {}

tolerations: []
