display: ":0"
xauthority: "~/.Xauthority"

enabled: true

legacy_compatibility: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-tmc-mid


labels:
  app: ska-tmc-mid
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

##  Order of instances resolution ##
# .Values.subarray_count 
# subarray_count, this will be expanded (1 to N inclusive) 
subarray_count: 2

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000

  ##  Order of instances resolution ##
  # .Values.global.dishes
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster, deviceServers.dishleafnode
  dish_devices: ["dishmaster", "dishleafnode"]
  dishes: ["001", "036", "063", "100"]

  namespace_dish:
    dish_names: []

  # Instance of the following devices can be expanded (1 to N inclusive) by using subarray_count
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"
  

  # fqdn for mid devices
  tmc_subarray_prefix: "ska_mid/tm_subarray_node"
  csp_subarray_ln_prefix: "ska_mid/tm_leaf_node/csp_subarray"
  sdp_subarray_ln_prefix: "ska_mid/tm_leaf_node/sdp_subarray"
  csp_master_ln_prefix: "ska_mid/tm_leaf_node/csp_master"
  sdp_master_ln_prefix: "ska_mid/tm_leaf_node/sdp_master"
  csp_subarray_prefix: "mid-csp/subarray"
  sdp_subarray_prefix: "mid-sdp/subarray"
  dish_suffix: "elt/master"
  csp_master: "mid-csp/control/0"
  sdp_master: "mid-sdp/control/0"

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.10
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-centralnode
    image: ska-tmc-centralnode
    tag: 0.14.3-dev.c4d684b46
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-subarraynode
    image: ska-tmc-subarraynode
    tag: 0.14.9-dev.cfdd7e286
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.14.2
    pullPolicy: IfNotPresent

cspmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.13.4
    pullPolicy: IfNotPresent

cspsubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.13.4
    pullPolicy: IfNotPresent

dishleafnode:
  image: 
    registry: artefact.skao.int
    image: ska-tmc-dishleafnode
    tag: 0.9.4
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi


deviceServers:
  centralnode:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    file: "data/centralnode_mid.yaml"
    DishLeafNodePrefix: "ska_mid/tm_leaf_node/d0"
    DishIDs: ["SKA001", "SKA036", "SKA063", "SKA100"]
    DishMasterPrefix: "elt"
    DishMasterPostfix: "master"
    DishVccConfig:
      DishVccUri: "car://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata"
      DishVccFilePath: "instrument/ska1_mid_itf/ska-mid-cbf-system-parameters.json"
      Enabled: "true"
      DishKvalueAggregationAllowedPercent: "100.0"

  subarraynode:
    enabled: true
    file: "data/subarraynode_mid.yaml"
    DishLeafNodePrefix: "ska_mid/tm_leaf_node/d0"
    DishIDs: ["SKA001", "SKA036", "SKA063", "SKA100"]
    DishMasterPrefix: "elt"
    DishMasterPostfix: "master"

  sdpsubarrayleafnode:
    enabled: true 
    file: "data/sdpsubarrayleafnode.yaml"

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"

  cspmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"

  cspsubarrayleafnode:
    enabled: true
    file: "data/cspsubarrayleafnode.yaml"

  dishleafnode:
    enabled: true
    file: "data/dishleafnode.yaml"

  mocks:
    enabled: false
    file: "data/mocks.yaml"
    dish: false
    csp: false
    sdp: false

nodeSelector: {}

affinity: {}

tolerations: []