---
display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: true
  sub-system:
    ska-tango-base:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.5
      pullPolicy: IfNotPresent
  ## Decide deployment mode of TMC. if standalone_mode is set to "true", then simulators for subsystem devices 
  # are deployed. If the value is "false", then simulators are not deployed.
  standalone_mode: "false"
  retry:
    - "--tries=10"
    - "--sleep=5"
  DEBUG: 5678

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
  itango:
    enabled: true
  jive:
    enabled: false

## SKUID
ska-ser-skuid:
  skuid:
    use_pv: false
    config:
      generator_id: mvp01

# tmc-leafnodes:
#   deviceServers:
#     mocks:
#       enabled: false
#       component:
#         csp: false
#         sdp: false
#         dish: false
#     sdpsln:
#       enabled: true
#     sdpmln:
#       enabled: true

# tmc_central_node:
#   enabled: true

# tmc_subarray_node:
#   enabled: true

ska-taranta:
  enabled: false


# tmc central node
ska-tmc-centralnode:
  enabled: true
  telescope: SKA-mid
  deviceServers:
    centralnode:
      enabled: true

# tmc subarraynode
tmc_subarray_node:
  deviceServers:
    mocks:
      enabled: false
      component:
        mccs: false
        csp: false
        sdp: false
        dish: false
    subarraynode:
      enabled: true

# tmc leaf nodes
tmc-leafnodes:
  deviceServers:
    mocks:
      enabled: false
      component:
        csp: false
        sdp: false
        dish: false
    sdpsln:
      enabled: true
    sdpmln:
      enabled: true

## tm-simulator
ska-tmc-mid-simulators:
  deviceServers:
    cspmastersimulator:
      enabled: false
     
    sdpmastersimulator:
      enabled: false
     
    cspsubarraysimulator:
      enabled: false
    
    sdpsubarraysimulator:
      enabled: false
