display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-tmc-mid

labels:
  app: ska-tmc
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  # skatmc:
  #   registry: artefact.skao.int/ska-telescope
  #   image: ska-tmc
  #   tag: 0.8.8
  #   pullPolicy: IfNotPresent

  ##  Order of instances resolution ##
  # .Values.global.dishes & .Values.global.subarray_count
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster, deviceServers.dishleafnode
  dish_devices: ["dishmaster", "dishleafnode"]
  dishes: ["01", "02", "03", "04"]

  # subarray_count, this will be expanded (1 to N inclusive) and applied to instances of:
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"
  subarray_count: 3
  
  ## Decide deployment mode of TMC. if standalone_mode is set to "true", then simulators for subsystem devices 
  # are deployed. If the value is "false", then simulators are not deployed.
  standalone_mode: "false"

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.5
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-centralnode
    tag: 0.3.9
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-subarraynode
    tag: 0.3.16
    pullPolicy: IfNotPresent
  
sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.8.16
    pullPolicy: IfNotPresent

# alarmhandler:
#   image:
#     registry: artefact.skao.int
#     image: ska-alarm-handler
#     tag: 0.1.7
#     pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  sdpsubarrayleafnode:
    enabled: true
    instances: ["01", "02", "03"]
    mid:
      file: "data/sdpsubarrayleafnode.yaml"
      SdpSubarrayFQDN: "mid_sdp/elt/subarray_1"
  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    SdpMasterFQDN: "mid_sdp/elt/master"
  subarraynode:
    enabled: true
    instances: ["01", "02", "03"]
    mid:
      file: "data/subarraynode_mid.yaml"
      DishLeafNodePrefix: "ska_mid/tm_leaf_node/d"
      CspSubarrayLNFQDN: "ska_mid/tm_leaf_node/csp_subarray01"
      SdpSubarrayLNFQDN: "ska_mid/tm_leaf_node/sdp_subarray01"
      CspSubarrayFQDN: "mid_csp/elt/subarray_01"
      SdpSubarrayFQDN: "mid_sdp/elt/subarray_1"
  centralnode:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    file: "data/centralnode_mid.yaml"
    CspMasterLeafNodeFQDN: "ska_mid/tm_leaf_node/csp_master"
    CspMasterFQDN: "mid_csp/elt/master"
    SdpMasterLeafNodeFQDN: "ska_mid/tm_leaf_node/sdp_master"
    SdpMasterFQDN: "mid_sdp/elt/master"
    DishLeafNodePrefix: "ska_mid/tm_leaf_node/d"
    NumDishes: 1
  # tm-alarmhandler:
  #   enabled: true
  #   instances: ["01"]
  #   file: "data/alarmhandler.yaml"


nodeSelector: {}

affinity: {}

tolerations: []
