---
apiVersion: v2
name: ska-oso-tmc-integration-tests
description: An umbrella Helm chart for OSO/SKA-TMC-Mid deployment.
type: application
version: 0.4.0
appVersion: 0.4.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Team Buttons
dependencies:
  - name: ska-tango-util
    version: 0.4.11
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 0.4.10
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tmc-mid
    # NOTE: When updating ska-tmc-mid chart version, also update the submodule
    # to the correct tag (see Update submodules section in README)
    version: 0.24.0
    repository: https://artefact.skao.int/repository/helm-internal
    alias: tmc-mid
    condition: ska-tmc-mid.enabled
  - name: ska-oso-tmcsim
    version: 0.4.0
    repository: file://../ska-oso-tmcsim
    condition: ska-oso-tmcsim.enabled
  - name: ska-oso-devpod
    version: 0.4.0
    repository: file://../ska-oso-devpod
    condition: ska-oso-devpod.enabled
  - name: ska-ser-skuid
    version: 3.3.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-skuid.enabled
  - name: ska-tango-alarmhandler
    version: 0.4.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-alarmhandler.enabled
  - name: ska-tmc-simulators
    version: 0.0.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tmc-simulators.enabled
  - name: ska-tango-taranta
    version: 2.10.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.4.4
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-oso-oet
    version: 6.3.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-oso-oet.enabled
  - name: ska-db-oda
    version: 6.1.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-db-oda.enabled
