---
display: ":0"
xauthority: "~/.Xauthority"

legacy_compatibility: true

global:
  retry:
    - "--sleep=1"
    - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.7
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent
  sdp:
    processingNamespace: ska-oso-tmc-integration-tests-sdp

ska-tango-base:
  enabled: true
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangodb:
    use_pv: false
  deviceServers:
    tangotest:
      instances: []

# Taranta
ska-taranta:
  enabled: false

ska-tango-taranta:
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int

ska-tango-tangogql:
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m  # 600m = 0.6 CPU
        memory: 512Mi  # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m  # 1000m = 1 CPU
        memory: 1024Mi  # 1024Mi = 1 GB mem
  ska-tango-examples:
    enabled: false

# Tmc-Mid
tmc-mid:
  labels:
    app: ska-oso-tmc-integration-tests
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      dish: true
      csp: true
      sdp: true

ska-oso-tmcsim:
  labels:
    app: ska-oso-tmc-integration-tests
  enabled: false

# SKUID
ska-ser-skuid:
  labels:
    app: ska-oso-tmc-integration-tests
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01

ska-tango-alarmhandler:
  labels:
    app: ska-oso-tmc-integration-tests
  enabled: false
  legacy_compatibility: true

ska-tmc-simulators:
  labels:
    app: ska-oso-tmc-integration-tests
  enabled: true
  deviceServers:
    cspmastersimulator:
      enabled: false

    weatherstation:
      enabled: false

    powersupplysimulator:
      enabled: false
