apiVersion: v2
name: ska-tmc-testing-mid
description: An umbrella Helm chart for SKA-TMC-Mid deployment.
type: application
version: 0.0.2
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Shraddha Bajare
    email: shraddhab.ska@gmail.com
dependencies:
  - name: ska-tango-util
    version: 0.4.10
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 0.4.8
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tmc-mid
    version: 0.15.2
    repository: file://../ska-tmc-mid
    alias: tmc-mid
  - name: ska-ser-skuid
    version: 0.3.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-skuid.enabled
  - name: ska-tango-alarmhandler
    version: 0.3.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-alarmhandler.enabled
  - name: ska-tmc-simulators
    version: 0.0.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tmc-simulators.enabled
  - name: ska-tango-taranta
    version: 2.3.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.3.7
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled