display: ":0"
xauthority: "~/.Xauthority"

legacy_compatibility: true

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.7
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

# Tmc-Mid
tmc-mid:
  labels:
    app: ska-tmc-integration
  enabled: true
  deviceServers:
    mocks:
      enabled: true
 
# SKUID
ska-ser-skuid:
  labels:
    app: ska-tmc-integration
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01
  
ska-tango-alarmhandler:
  labels: 
    app: ska-tmc-integration
  enabled: true

ska-tmc-simulators:
  labels: 
    app: ska-tmc-integration
  enabled: true
  deviceServers:
    cspmastersimulator:
      enabled: false
    
    weatherstation:
      enabled: true
    
    powersupplysimulator:
      enabled: true
