---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "ska-oso-tmcsim.name" .}}-{{.Release.Name}}-devpod-environment
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "ska-oso-tmcsim.labels" . | indent 4}}
    component: {{template "ska-oso-tmcsim.name" .}}
    domain: environment
    function: devpod-environment
    intent: development
data:
  ODA_URL: {{.Values.devpod.env.oda_url}}
  TANGO_HOST: {{if .Values.global.tango_host -}} {{.Values.global.tango_host}} {{- else -}} tango-databaseds-{{.Release.Name}}:10000 {{- end}}
  SHELL: /usr/bin/bash
