display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: TMC-low
telescope: SKA-low
subsystem: ska-tmc-low

labels:
  app: ska-tmc-low
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000

  ##  Order of instances resolution ##
  # .Values.global.dishes & .Values.global.subarray_count
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # subarray_count, this will be expanded (1 to N inclusive) and applied to instances of:
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "sdpsubarrayleafnode"
  subarray_count: 3

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.5
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.8.24
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  sdpsubarrayleafnode:
    subarray_count: 3
    enabled: true
    instances: ["01", "02", "03"]
    file: "data/sdpsubarrayleafnode.yaml"

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    SdpMasterFQDN: "mid-sdp/control/0"


  mocks:
    enabled: false
    file: "data/mocks.yaml"


nodeSelector: {}

affinity: {}

tolerations: []
