display: ":0"
xauthority: "~/.Xauthority"

enabled: true

legacy_compatibility: true

system: TM-low
telescope: SKA-low
subsystem: ska-tmc-low

labels:
  app: ska-tmc-low
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000

  ##  Order of instances resolution ##
  # .Values.global.dishes & .Values.global.subarray_count
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # subarray_count, this will be expanded (1 to N inclusive) and applied to instances of:
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"
  subarray_count: 2

dsconfig:
  configuration_file: data/tmc-low-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.10
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-centralnode
    image: ska-tmc-centralnode
    tag: 0.10.4
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-subarraynode
    image: ska-tmc-subarraynode
    tag: 0.11.20
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.13.1
    pullPolicy: IfNotPresent

cspmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.9.0
    pullPolicy: IfNotPresent

cspsubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.9.0
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  centralnode:
    enabled: true
    instances: ["01"]
    subarray_count: 2
    file: "data/centralnode.yaml"

  subarraynode:
    enabled: true
    instances: ["01", "02"]
    file: "data/subarraynode.yaml"

  sdpsubarrayleafnode:
    enabled: true
    instances: ["01", "02"]
    file: "data/sdpsubarrayleafnode.yaml"

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    SdpMasterFQDN: "low-sdp/control/0"

  cspmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"
    CspMasterFQDN: "low-csp/control/0"

  cspsubarrayleafnode:
    enabled: true
    instances: ["01", "02"]
    file: "data/cspsubarrayleafnode.yaml"

  mocks:
    enabled: false
    file: "data/mocks.yaml"


nodeSelector: {}

affinity: {}

tolerations: []