k8s-test-mid:
  # allow_failure: true
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  tags:
    - k8srunner
  variables:
    CONFIG: mid
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG'
    TELESCOPE: SKA-mid
  before_script:
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - 'make help | grep k8s-test'
    - make k8s-install-chart TELESCOPE=SKA-mid
    - make k8s-wait TELESCOPE=SKA-mid
  script:
    - make k8s-test TELESCOPE=SKA-mid
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-mid
    auto_stop_in: 1 minute
  rules:
    - exists:
        - tests/**/*

stop-k8s-test-mid:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  tags:
    - k8srunner
  when: manual
  variables:
    CONFIG: mid
    TELESCOPE: SKA-mid
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG'
  script:
    - make k8s-uninstall-chart TELESCOPE=SKA-mid
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all
    - make k8s-delete-namespace TELESCOPE=SKA-mid
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    action: stop

